# Generated by Django 5.2.4 on 2025-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meu_app", "0002_categoria_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
