# Generated by Django 5.2.4 on 2025-08-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meu_app", "0003_produto_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("contato", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
